name: ahswat4android
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.2
  sensors_plus: ^6.1.2
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  bloc: ^9.0.0
  url_launcher: ^6.3.0
  vibration: ^3.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Put your Lottie JSON here (directory works too)
  assets:
    - asset/wavy.json
  
